version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{project_slug}}_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./{{project_slug}}/.env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: {{project_slug}}_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./{{project_slug}}/.env

  redis:
    image: redis:3.2
