version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  db:
    image: {{project_slug}}_postgres:local
    build:
      context: .
      dockerfile: ./compose/db/Dockerfile
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups

  web:
    image: {{project_slug}}_web:local
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    env_file: .env
    volumes:
      - .:/web_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: /start